name: SOI 25k tile run

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

on: 
  workflow_dispatch:

jobs:

  Run-SOI-Tiling:
    needs: Check-For-Work
    timeout-minutes: 600
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Setup swap
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 12

      - uses: actions/checkout@v4.1.7

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Get current date
        run: echo "date=$(date +'%d%b%Y')" >> $GITHUB_OUTPUT
        id: date

      - name: Retile
        id: retile
        run: |
          mkdir -p temp
          TMPDIR=./temp 
          GDAL_VERSION=$(gdalinfo --version | cut -d"," -f1 | cut -d" " -f2)
          echo "GDAL_VERSION=$GDAL_VERSION"
          uvx --with numpy --with pillow --with gdal==$GDAL_VERSION --from topo-map-processor retile-e2e \
              --pmtiles-release 25k-nhp-pmtiles \
              --gtiffs-release 25k-nhp-georef \
              --pmtiles-prefix SOI-NHP-25k \
              --bounds-file-tiled "bounds.geojson"
