name: SOI 25k tile run

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

on: 
  workflow_dispatch:

jobs:

  Run-SOI-Tiling:
    timeout-minutes: 600
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:

      - name: Space check0
        run: |
          df -h .
          free -h

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Space check1
        run: |
          df -h .
          free -h

      - uses: actions/checkout@v4.1.7

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev build-essential python3-dev

      - name: Retile
        id: retile
        run: |
          mkdir -p temp
          TMPDIR=./temp 
          GDAL_VERSION=$(gdalinfo --version | cut -d"," -f1 | cut -d" " -f2)
          echo "GDAL_VERSION=$GDAL_VERSION"
          uv venv
          uv pip install numpy pillow
          uv pip install --no-build-isolation --no-cache-dir --force-reinstall GDAL==${GDAL_VERSION}
          uv pip install topo-map-processor
          uv run retile-e2e \
              --pmtiles-release 25k-nhp-pmtiles \
              --gtiffs-release 25k-nhp-georef \
              --pmtiles-prefix SOI-NHP-25k \
              --bounds-file-tiled "bounds.geojson"
