name: SOI Weekly 50k parse run

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

on: 
  workflow_run:
    workflows:
      - "SOI Weekly 50k pull run"
    type:
      - completed
  workflow_dispatch:


jobs:
  Check-For-Work:
    runs-on: ubuntu-22.04
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    env:
      GH_TOKEN: ${{ github.token }}
    outputs: 
      work_item_count: ${{ steps.work.outputs.num_items }}  
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: astral-sh/setup-uv@v5
      - name: Check for work
        id: work
        run: |
          cd 50k/osm
          mkdir data
          util/get_work_for_parser.sh data/to_parse.txt
          cat data/to_parse.txt
          num_items=$(wc -l data/to_parse.txt | tr -s " " | cut -d" " -f1)
          echo "num_items=$num_items"
          echo "num_items=$num_items" >> $GITHUB_OUTPUT

  Run-SOI-Parsing:
    needs: Check-For-Work
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' && needs.Check-For-Work.outputs.work_item_count != '0'
    timeout-minutes: 600
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Setup swap
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 12
      - uses: actions/checkout@v4.1.7

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Restore parse tools from cache
        uses: actions/cache/restore@v4
        with:
          path: 50k/osm/bin/
          key:  soi-parse-tools-v5
        id: tools-cache

      - name: Install tools
        if: ${{ steps.tools-cache.outputs.cache-hit != 'true' }}
        run: |
          cd 50k/osm
          if [[ ! -f bin/mutool ]]; then
            sudo apt-get install -y llvm
            wget -P util https://raw.githubusercontent.com/ramSeraph/soi_common/refs/heads/main/utils/mupdf.patch
            wget -P util https://raw.githubusercontent.com/ramSeraph/soi_common/refs/heads/main/utils/build_mutool.sh
            chmod +x util/build_mutool.sh
            CXX=clang++ AR=llvm-ar util/build_mutool.sh
          fi

      - name: Save parse tools to cache
        if: ${{ steps.tools-cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: 50k/osm/bin/
          key:  soi-parse-tools-v5

      - name: Restore ancillary files from cache
        uses: actions/cache/restore@v4
        with:
          path: |
            50k/osm/data/index_50k.geojson
            50k/osm/data/SOI_FONTS.zip
          key: 'SOI-parse-basefiles-v1'
        id: base-files-cache

      - name: Download Ancillary data
        if: ${{ steps.base-files-cache.outputs.cache-hit != 'true' }}
        run: |
          cd 50k/osm

          [[ -f data/SOI_FONTS.zip ]] || wget -P data/raw/ https://github.com/ramSeraph/india_topo_maps/releases/download/soi-ancillary/SOI_FONTS.zip 
          [[ -f data/index_50k.geojson ]] || wget -P data/ https://github.com/ramSeraph/india_topo_maps/releases/download/soi-ancillary/index_50k.geojson

          cd data
          unzip SOI_FONTS.zip


      - name: Save ancillary files to cache
        if: ${{ steps.base-files-cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: |
            50k/osm/data/index_50k.geojson
            50k/osm/data/SOI_FONTS.zip
          key: 'SOI-parse-basefiles-v1'


      - name: Get current date
        run: echo "date=$(date +'%d%b%Y')" >> $GITHUB_OUTPUT
        id: date

      - name: Restore parse run data from cache
        uses: actions/cache/restore@v4
        with:
          path: |
            50k/osm/data/raw/*.pdf
            50k/osm/export/gtiffs/
          key:  soi-gcs-parse-v4-${{ steps.date.outputs.date }}-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            soi-gcs-parse-v4-${{ steps.date.outputs.date }}-${{ github.run_number }}-
            soi-gcs-parse-v4-${{ steps.date.outputs.date }}-


      - name: Parse SOI sheets
        run: |
          cd 50k/osm

          util/get_work_for_parser.sh data/to_parse.txt
          uvx --from gh-release-tools download-from-release -r '50k-osm-orig' -d 'data/raw' -f data/to_parse.txt -e '.pdf'

          mkdir -p export/gtiffs/

          echo "Running parse.py"
          GDAL_VERSION=$(gdalinfo --version | cut -d"," -f1 | cut -d" " -f2)
          FROM_LIST=data/to_parse.txt uv run --with GDAL==${GDAL_VERSION} parse.py
          
          echo "Parse run completed, generating lists and uploading to release"
          uvx --from gh-release-tools upload-to-release -r '50k-osm-georef' -d 'export/gtiffs' -e '.tif' 

          echo "Generating lists"
          uvx --from gh-release-tools generate-lists -r '50k-osm-georef' -e '.tif'

          echo "Generating bounds file and uploading"
          gh release download '50k-osm-georef' -p bounds.geojson
          uvx --from topo-map-processor collect-bounds -u -o bounds.geojson -b export/bounds
          gh release upload '50k-osm-georef' bounds.geojson --clobber
          rm data/bounds.geojson

          rm -rf data/raw/* || true
          rm -rf export/gtiffs/* || true
        timeout-minutes: 600
 
      - name: Save parse run data to cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            50k/osm/data/raw/*.pdf
            50k/osm/export/gtiffs/
          key:  soi-gcs-parse-v4-${{ steps.date.outputs.date }}-${{ github.run_number }}-${{ github.run_attempt }}


  SOI-Parse-Failure-Notify:
    needs: 
      - Run-SOI-Parsing
      - Check-For-Work
    if: always() && ( needs.Check-For-Work.result == 'failure' || needs.Run-SOI-Parsing.result == 'failure' )
    uses: ./.github/workflows/common-pb-alert.yml
    secrets: inherit
    with:
      title: "SOI Parse Run Failed"
      which-run: "self"

  #BuildDocs:
  #  needs: 
  #    - Run-SOI-Parsing
  #    - Check-For-Work
  #  uses: ./.github/workflows/docs.yml
  #  secrets: inherit

